# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BlackLagerMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x42lackLagerMessage.proto\"z\n\x11\x42lackLagerMessage\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\"\n\x04text\x18\x02 \x01(\x0b\x32\x0f.BlackLagerTextH\x00\x88\x01\x01\x12\x1e\n\x07Persona\x18\x03 \x01(\x0b\x32\x08.PersonaH\x01\x88\x01\x01\x42\x07\n\x05_textB\n\n\x08_Persona\"H\n\x06Wallet\x12\x1d\n\x0bmy_personas\x18\x01 \x01(\x0b\x32\x08.Persona\x12\x1f\n\rpeer_personas\x18\x02 \x03(\x0b\x32\x08.Persona\"W\n\x0e\x42lackLagerText\x12\x15\n\rsignedMessage\x18\x01 \x01(\x0c\x12\x15\n\rsenderNodeNum\x18\x02 \x01(\x05\x12\x17\n\x0freceiverNodeNum\x18\x03 \x01(\x05\"\x97\x01\n\x07Persona\x12\x12\n\nlocal_name\x18\x01 \x01(\t\x12\x13\n\x0bmac_address\x18\x02 \x01(\t\x12\x10\n\x08node_num\x18\x03 \x01(\x05\x12\x12\n\npublic_key\x18\x04 \x01(\x0c\x12\x13\n\x0bprivate_key\x18\x05 \x01(\x0c\x12\x0b\n\x03uid\x18\x06 \x01(\x0c\x12\x0c\n\x04mask\x18\x07 \x01(\x0c\x12\r\n\x05owned\x18\x08 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BlackLagerMessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLACKLAGERMESSAGE._serialized_start=27
  _BLACKLAGERMESSAGE._serialized_end=149
  _WALLET._serialized_start=151
  _WALLET._serialized_end=223
  _BLACKLAGERTEXT._serialized_start=225
  _BLACKLAGERTEXT._serialized_end=312
  _PERSONA._serialized_start=315
  _PERSONA._serialized_end=466
# @@protoc_insertion_point(module_scope)
